name: ShowRatesLoggerGUI Pipeline

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    DOTNET_VERSION: '9.0.x'
    BUILD_CONFIGURATION: 'Release' 

jobs:
    build:
        name: Build
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

            - name: Publish
              run: dotnet publish -c ${{ env.BUILD_CONFIGURATION }} -o ./publish --self-contained

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: app-package
                path: ./publish
                retention-days: 1

    release:
      name: Create Release
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      permissions:
        contents: write

      steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: app-package
            path: release-files

        - name: Verify Files
          run: |
            echo "Contents of release-files:"
            ls -R release-files

        - name: Create Release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v${{ github.run_number }}
            name: Release v${{ github.run_number }}
            body: |
              Automatic release of build ${{ github.run_number }}
              Commit: ${{ github.sha }}
            files: |
              release-files/**/*